#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ktls
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="ktls"
desc="Enable Kernel TLS"
rcvar="ktls_enable"
start_cmd="${name}_start"
stop_cmd=":"

ktls_start()
{

	sysctl -q kern.ipc.tls.enable=1 > /dev/null
	err=$?
	if [ "${err}" -ne 0 ]; then
		warn "kernel must be built with options KERN_TLS for ktls"
		return "${err}"
	fi
	sysctl kern.ipc.mb_use_ext_pgs=1 > /dev/null

	#
	# Load ktls_ocf and optionally aesni
	#
	load_kld ktls_ocf
	if checkyesno ktls_aesni_enable; then
		load_kld aesni
	fi
}

load_rc_config $name
run_rc_command "$1"
