#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: rpctlscd
# REQUIRE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="rpctlscd"
desc="NFS over TLS client side daemon"
rcvar="rpctlscd_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name

run_rc_command "$1"
