#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: rpctlssd
# REQUIRE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="rpctlssd"
desc="NFS over TLS server side daemon"
rcvar="rpctlssd_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/rpctlssd/cert.pem /etc/rpctlssd/key.pem"
extra_commands="reload"


load_rc_config $name

run_rc_command "$1"
